sonar.projectKey=blog-pessoal-dotnet
sonar.projectName=Blog Pessoal Backend ASP.NET Core
sonar.sourceEncoding=UTF-8
sonar.sources=BlogPessoal/BlogPessoal
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**,**/*.log
